@startuml start_game
!theme mars
skinparam Style strictuml

actor "Player" as Player #green
participant "Playground" as Playground #blue
participant "Active block" as Block #orange
participant "Wall" as Wall #red
participant "ScorePanel" as Panel #green

Player -[#blue]> Playground : start_game
Playground -[#orange]> Block : generateNextBlock
Playground -[#red]> Wall : initWallHeight
Playground -> Playground : moveBlock down
Player -[#blue]> Playground : moveLeft
alt Check collision
    Playground -> Playground : moveBlock down
else Block collision
    Playground -> Wall : transform block to wall
    Playground -> Block : generateNextBlock
end
group 
@enduml
