@startuml start_game
!theme mars
skinparam Style strictuml

actor "Player" as Player #green
participant "Playground" as Playground #blue
participant "Active block" as Block #orange
participant "Wall" as Wall #red
participant "ScorePanel" as Panel #green

Player -[#blue]> Playground : start_game
Playground -[#orange]> Block : generateNextBlock
Playground -[#red]> Wall : initWallHeight

alt Check collision
group game check loop
    Playground -> Playground : moveBlock down
else Block collision
    Playground -[#red]> Wall : transform block to wall
    alt Check full line
    group check full line
        Wall -[#red]> Wall : check full line
    else No full line
        Wall -[#red]> Wall : update wall
    end
    end
    Wall -[#red]> Wall : check full line
    Playground -[#orange]> Block : generateNextBlock
end

Player -[#blue]> Playground : moveLeft
group 
@enduml
